mumble:
  user: Bot
  server: localhost:64738
  alias:
    help: play help
  hooks:
    first_join:
      default: sticker welcome
    join:
      default: play welcome
  sounds:
    hold: ./sounds
    clips: ./sounds
# Uncomment to enable execution of scripts
#  scripts:
#    directory: ./scripts

telegram:
  token: "<secret>"
  target: ""
  stickers:
#    label:
#      file:
#        fileid: <file id>

matrix:
  server: "https://matrix.org"
  user: ""
  token: "<secret>"
  room: ""
  stickers:
#    name:
#      url: mxc://...
#      body: "Some text"
#      info:
#        mime_type: image/webp
#        h: 203
#        w: 256
#        size: 101312
